name: CI

on:
  pull_request:
    types:
      - "open"
      - "synchronize"
      - "edit"

jobs:
  check_sv:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3
      
      - uses: amannn/action-semantic-pull-request@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

  tests: 
    needs: check_sv
    runs-on: "ubuntu-latest"
    name: Run Unit Tests
    steps:
      - name: Run Unit Tests
        run: echo "Hello"