name: Release

on:
  push:
    branches:
      - "main"
  
jobs:
  release:
    runs-on: "ubuntu-latest"
    env: 
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persists-credentials: false

      - uses: actions/setup-node@v3
        with: 
          node-version: 18

      - name: Install Deps
        run: npm install

      - name: Semantic Release
        run: npx semantic-release --ci
        